[package]
name = "parser"
version = "0.0.1"
edition = "2021"

[dependencies]
tree-sitter = "0.20.9"
discovery = { path = "../discovery" }
thiserror = "1"
itertools = "*"
include_dir = "0"

[dev-dependencies]
speculoos = "0"

[build-dependencies]
cc = "1"
npm_rs = "1"
