[package]
name = "discovery"
version = "0.0.1"
edition = "2021"

[dependencies]
detect-lang = "0"
walkdir = "2"

[dev-dependencies]
tempfile = "3"
difference = "2"
utilities = { path = "../utilities" }
speculoos = "0"
